### ISSUE TITLE
How to adjust the position of the bottom text?

### ISSUE THREAD

**Issue by jeghers** [palerdot/react-d3-speedometer#10]
Hi all,

My text at the bottom is getting covered by the bottom of the needle, and I cannot find a way to adjust it.  Can anyone help, or this this a bug needing code change?
![gauge](https://user-images.githubusercontent.com/6721949/33034388-80c3eb78-cddc-11e7-81cd-21a317629036.jpg)

**Comment by palerdot** [comment]
Thanks for raising this issue. This is not configurable right now. I will make changes in next minor version so that the text is little below and it is visible. Regarding, having it configurable, it is not yet decided and might take some time to release. Watch out for next minor release 0.2.1, which hopefully should have this changes.

**Comment by jeghers** [comment]
Cool, thanks!

**Comment by palerdot** [comment]
This issue is addressed in `v0.2.1` and released - https://www.npmjs.com/package/react-d3-speedometer.

Attached sample image of fixed positioning in my test case. Please note, this is an issue only in smaller dimension speedometers and beyond a certain threshold if the dimensions are too small, there will be challenges in displaying. But, I think, this tweak will work fine for reasonable dimensions and should address your issue too.
![small speedometer text alignment](https://user-images.githubusercontent.com/4299398/33082358-9744073a-cf02-11e7-8d2e-2beba75d6c27.png)

I'm closing this issue for now. Please reopen if you still feel there is something to be addressed regarding this.

**Comment by jeghers** [comment]
Looks great. Thanks again.

**Comment by jeghers** [comment]
Looks good now, thanks again.
