### ISSUE TITLE
Dependency error with baseGetTag?

### ISSUE THREAD

**Issue by ericholmescodes** [palerdot/react-d3-speedometer#103]
![Capture](https://user-images.githubusercontent.com/68088236/98900737-3f781d80-2467-11eb-9b27-1455cb681391.PNG)

Tried manually installing all the dependencies and that didn't work. I can npm start just fine but building it gives this error.

**Comment by palerdot** [comment]
@ericholmescodes 

This library uses `lodash-es` which uses `es6 exports`. Your build setup does not understand `es6 modules`. If you are using `babel`, please try and integrate https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs so that your setup understands `es6 exports`.

You can also try integrating https://github.com/lodash/babel-plugin-lodash

Alternatively, if you are using `React 16`, you can pin the version to `0.10.0`, since `lodash-es` was added in `v0.11.0` (though I would advise against this. better way is to make your build setup understand es6 module exports)

I'm closing this issue since this is related to build setup of your project. Please reopen if you are still stuck after upgrading your project build setup.
