### ISSUE TITLE
placing decimal values in speeddometer

### ISSUE THREAD

**Issue by KaranSofat** [palerdot/react-d3-speedometer#11]
How can i place decimal value under needle?

**Comment by palerdot** [comment]
Right now it is not configurable. To format the values, d3format(https://github.com/d3/d3-format) is used and currently, by default values are formatted as integers. I will make this as configurable so that it accommodates wide variety of formatting (as per d3Format) including decimals. Watch out for next release as mostly it might have this change.

**Comment by palerdot** [comment]
This issue is fixed and released in the new release - 0.2.2. By default, without any changes, decimal values should appear. To have more control on the format, you can use the newly introduced configuration `valueFormat`. I'm closing this issue as this release should address your issue. Please reopen if you feel still there are issues.
