### ISSUE TITLE
Is it possible to set label on segments ? 

### ISSUE THREAD

**Issue by shakti03** [palerdot/react-d3-speedometer#14]
Please help if possible to draw chart like this.
![speedometer](https://user-images.githubusercontent.com/9641598/34913732-53254322-f92b-11e7-883a-4a5bfcba0532.png)

**Comment by palerdot** [comment]
Currently the labels are automatically calculated based on `maxValue`, 'minValue' and `segments`. This may not be possible at all, as per the library functionality, there will be 5 values for your chart instead of 4 you have mentioned. I'm afraid this is not possible at all as far as I see. So I'm closing this issue.
