### ISSUE TITLE
Allow `segmentValueFormatter` to return a DOM node

### ISSUE THREAD

**Issue by yosi1314** [palerdot/react-d3-speedometer#169]
Hi! 
Would it be possible to allow `segmentValueFormatter` to return an object instead of only string?
For example instead of a regular text I want to return an svg or a react component.
Thanks in advance!

**Comment by palerdot** [comment]
No. It is not possible and unlikely to be available in the future. This would lead to additional security issues if the library is not able to infer what is being injected into the code. Unless otherwise the function signature specifically mentions a DOM markup as a return value (none so far), optional injection of dom nodes will not be possible.

**Comment by palerdot** [comment]
This will also lead to alignment/display problems with the injected HTML messing up with current speedometer structure. To accommodate that, further changes may have to made to the library which will lead to an uncontrollable circle. For these reasons, this will not be considered.
