### ISSUE TITLE
Showing empty speedometer when invalid data is passed to react-d3-speedometer

### ISSUE THREAD

**Issue by alamsha** [palerdot/react-d3-speedometer#21]
I love this gauge. I am updating the value from a parent component. Sometimes it passes some sort of undefined value and the app crashes. If that happens, i would like to have an empty gauge or a message "INVALID VALUE" embedded on top of the gauge without crashing. It shall continue to work normal when it gets valid data. How can i do it? Thanks.
....................................
**Error Message:**
![error](https://user-images.githubusercontent.com/11894771/40244350-a7b11cfe-5ad3-11e8-8c67-f43826d3686b.png)

**Comment by palerdot** [comment]
The best way to deal with your situation is, whenever you get an invalid value, just draw an empty speedometer by passing following values
```javascript
<ReactSpeedometer 
    segments={1}
    value={0}
    minValue={0}
    maxValue={0}
    currentValueText={'INVALID DATA'}
    startColor={'#YOUR_PREFERRED_COLOR'}
    needleColor={'#YOUR_PREFERRED_COLOR'}
/>
```
which might look something like
![screen shot 2018-05-18 at 9 51 50 pm](https://user-images.githubusercontent.com/4299398/40246270-d3c93e22-5ae5-11e8-857a-988209ce0f8d.png)

For now, I'm closing this issue, since it is not directly related to the speedometer component (as speedometer gauge always assumes some valid data to be shown), and also since you can achieve something similar as mentioned above.

**Comment by alamsha** [comment]
Thank you so much  :+1:  . The error message was part of JS engine. At the moment, i am just reloading the page on error.
```
function reloadpage () {
  window.location.reload(true)
}
window.onerror = reloadpage
```
