### ISSUE TITLE
Unequal segments 

### ISSUE THREAD

**Issue by snehatuteja** [palerdot/react-d3-speedometer#24]
Is there a way we can have unequal segments based on a percentage for the dial?

**Comment by palerdot** [comment]
Right now, the segments equally divide the dial/arc between `min` and `max`. I'm not sure about the feasibility of this feature and even if possible not sure about any possible release in the near future.

**Comment by palerdot** [comment]
For now, this feature will not ship as it involves some additional features like giving custom values instead of segments, so that segments should be automatically calculated based on the values. I will reopen this issue in case this feature lands up in the library. For now, this feature will not ship
