### ISSUE TITLE
Configuring the needle size.

### ISSUE THREAD

**Issue by thanh121094** [palerdot/react-d3-speedometer#34]
Hi all, Hi @palerdot ,
I'm using react-d3-speedometer for my project and I have a problem with the size of needle.
I can not find any solution about set size of the needle which is too long. 
Observe the following image. In the left image, the text value is overrided by the needle. I can only set the needle color by the needleColor property.
![333333](https://user-images.githubusercontent.com/24429197/48829945-135cc100-eda6-11e8-9a62-a7566a4d532a.png)

Can it be resolved with d3-speedometer? Thanks.
Thanhnv from Thinklabs - Vietnam

**Comment by palerdot** [comment]
I will add a new config `needleHeightRatio` which should be between `0` and `1`. Right now, it is `0.9` which is default. You can adjust this to your needs something like `0.7` which will reduce the needle height. Since this is not a breaking change, I will just release it as `0.4.2` patch with extra `needleHeightRatio` config

**Comment by palerdot** [comment]
`needleHeightRatio` config is added and published in `v0.4.2`. You can check a live example [here](https://palerdot.in/react-d3-speedometer/?selectedKind=react-d3-speedometer&selectedStory=configure%20needle%20length&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

Please update to `0.4.2` version and hope this resolves your issue. Please reopen this issue. if you face any difficulties
