### ISSUE TITLE
Removing All Segment Labels

### ISSUE THREAD

**Issue by darcyrailip** [palerdot/react-d3-speedometer#43]
I figured I could set `maxSegmentLabels={0}` and it wouldn't show any segment labels, however it just ends up re-inheriting the `segments` value.

Any thought on allowing us to hide the segment labels?

**Comment by palerdot** [comment]
@darcyrailip Currently, `maxSegmentLabels` is explicitly checked for a positive number (>0, if negative default `segments` will be inherited) since the assumption was people would need some kind of label to make sense out of visualisation ... Maybe I should relax that if no label should be shown ... I will make this change and update this issue ... Mostly, it should be done and released max in next 2-3 days ...

**Comment by palerdot** [comment]
This enhancement is added in `0.5.7` version. Here is  a `sandbox` - https://codesandbox.io/s/confident-swanson-hvl34

Please make sure you have `0.5.7` version as `v0.5.6` (intermediate previous version) was deprecated because of a missing dependency error thrown ... 

Please reopen if you still face any issues with latest `0.5.7` version ...
