### ISSUE TITLE
Just Feedback Trendpoints or lables not available 

### ISSUE THREAD

**Issue by RGKrish183** [palerdot/react-d3-speedometer#50]
Hi,

Really Cool Npm package, its very easy to integrate.

I just tried to integrate your npm packages, but you missed somthing i guess, your providing the **customSegmentStops** but there is dont have options to changes values name.

>    customSegmentStops={[0, 500, 750, 1000]}
>    In this case there will be `4` segments (0-500, 500-750, 750-1000)
>
>    In my case 0-500 label is Low, 500-750 label is Medium, 750-1000 label is High 

Just take it as feedback, and also provide some send feedback option in your website. 

FYI, So, Currently i have using fushionchart.com that option they are providing.

Thanks,
Gopal R.

**Comment by palerdot** [comment]
Thanks for the feedback. This issue is already tracked here - https://github.com/palerdot/react-d3-speedometer/issues/33. There are few things to consider for implementing this feature like how to accomodate text when the segment size is few small like [this example](https://palerdot.in/react-d3-speedometer/?path=/story/react-d3-speedometer--configuring-values) ... The updates for this issue will be updated in the linked issue
