### ISSUE TITLE
Speedometer has 0 height and width with FluidWidth when application starts in iframe

### ISSUE THREAD

**Issue by Xambey** [palerdot/react-d3-speedometer#69]
FluidWidth works incorrect when application starts in iframe. When the speedometer is being drawn, the clientWidth and clientHeight of the parent component dont have time to get the dimensions set for it, as a result of the fact that in this state they are 0, the speedometer gets 0 width and height. How can I fix it?

In this case, only enabling forceRender mode and then disabling it helps, but it is very crooked and may one day not work as it should on some weak mobile device:
```javascript
    componentDidMount(){
        setTimeout(() => {
            this.setState({
                forceRender: false
            })
        }, 500);

        setInterval(() => {
            this.setState({
                value: this.state.value + 10
            })
        }, 1000);
    }
```

**Comment by palerdot** [comment]
This looks like a limitation of the environment/sandbox (i.e iframe) in which this component is run. Alternatively, you can also delay rendering the `<ReactSpeedometer />` till we get the parent `height/width` and then normally render with `forceRender` enabled ... something like 
```
state = {
   loadSpeedometer: false
}

componentDidMount() {
   delay(() => {
      // check if the dimensions are present 
      const loaded = this.isIframeDimensionsLoaded()
     // and if present
     this.setState({
         loadSpeedometer: true
     })
  }, 1000)
}

isIframeDimensionsLoaded = () => {}

// inside render of your component
render () {
   return this.state.loadSpeedometer ? <ReactSpeedometer /> : null
}
```
I'm closing this issue, since this is more of a limitation of the the sandbox (iframe) in which code is run.
