### ISSUE TITLE
Right to Left Speedometer/Edit Stop Labels

### ISSUE THREAD

**Issue by YairVaknin** [palerdot/react-d3-speedometer#74]
Hello,

would it be at all possible to add support to a speedometer which has its minValue on the right and its maxValue on the left and as the current value grows it goes from right to left instead of from left to right as it's currently done?

EDIT: if this is not possible, might it be possible to control the texts that's displayed over the segments' stops? Right now it seems to not be changeable and is set to be the values of the stops.

Thanks.

**Comment by palerdot** [comment]
Hi @YairVaknin,
> which has its minValue on the right and its maxValue on the left and as the current value grows it goes from right to left 

You can achieve this behaviour/effect by manually giving desired values for - `customSegmentStops`, `minValue`, `maxValue`. For eg:

```javascript
       <ReactSpeedometer
          minValue={1000} // start from your max value so that it shows on left
          maxValue={0} // end with your min value so that is shows on right
          value={333}
          needleHeightRatio={0.7}
          maxSegmentLabels={5}
          segments={3}
          customSegmentStops={[1000, 900, 750, 500, 0]} // manually define stops
          segmentColors={["firebrick", "tomato", "gold", "limegreen"]}
          textColor={"#333"}
        />
```
The only caveat will be the initial needle animation will be animated from left to right  ... but subsequent updates will correctly point to your value and flow from right to left ... As for the initial needle animation flowing from left to right, there are no plans to change this behaviour ... but this should be close to the behaviour/effect you would like to achieve.

You can see a live sandbox here - https://codesandbox.io/s/competent-rain-iyu2j?file=/src/App.js:281-624

I'm closing this issue since you could achieve this behaviour by manually controlling `customSegmentStops`, `minValue`, `maxValue` (barring the initial needle animation for which there are no plans to change this behaviour)
